dist: bionic
sudo: required
services: docker
language: bash

addons:
  apt:
    packages:
      - build-essential
      - libzmq3-dev
      - libzmqpp-dev
      - libgtest-dev
      - libprotobuf-dev
      - protobuf-compiler
      - curl
      - gnupg2
      - lsb-release
      - libboost1.65-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
