package(default_visibility = ['//visibility:public'])

cc_library(
  name = 'routines',
  visibility = ['//visibility:public'],
  hdrs = [
    'routine.h',
    'programmed_routine.h',
    'line_highlight_routine.h',
    'outline_routine.h',
    'movie_theater_routine.h',
    'fade_routine.h',
  ],
  deps = [
    "//src/display/visualizer:visualizer",
    '//src:messages_cpp'
  ],
)
