package(default_visibility = ['//visibility:public'])

cc_library(
  name = 'stdout_visual',
  visibility = ['//visibility:public'],
  srcs = [
    'stdout_visual.cc'
  ],
  hdrs = [
    'stdout_visual.h'
  ],
  deps = [
    '//src/display/visualizer:visualizer',

    '@SDL2//:SDL2'
  ],
)
